<%@ page contentType="text/html; charset=gb2312" %>
<HTML>
<HEAD>
<TITLE>
在线书城
Template
</TITLE>
<!--CharSet-->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=gb2312">
<link rel="stylesheet" href="images/CSS.CSS" type="text/css">
<style type="text/css">
<!--
-->
</style>
<SCRIPT ID=clientEventHandlersJS LANGUAGE=javascript>
<!--

function window_onload() {
<!--Page.OnLoad-->
}

//-->
</SCRIPT>
</HEAD>
<BODY BGCOLOR=#3E79A6 leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" onload="return window_onload()">
<!--Counter-->
<!--Something Here-->
<table width="778" border="0" cellspacing="0" cellpadding="0" align="center" height="135">
  <tr> 
    <td height="110" width="540" background="images/index_top1.gif" valign="top"> 
      <table border="0" cellspacing="0" cellpadding="0" width="540" align="center">
        <tr> 
          <td height="25" width="340"> <font color="#FFFFFF"><b></b></font> 
            <div align="center"></div>
          </td>
          <td height="25" width="200">&nbsp;</td>
        </tr>
        <tr> 
          <td height="30" width="500"> 
            <div align="center"><font color="#FFFFFF"><b><font size="5">
<!--Your Company Name-->
在线书城内部管理 
              </font></b></font></div>
          </td>
          <td height="30" width="200">&nbsp;</td>
        </tr>
        <tr> 
          <td height="30" width="500"> 
            <div align="center"><font size="4" color="#FFFFFF">
<!--Your Company Name.English-->
Admin Ling du Book Shop
</font> </div>
          </td>
          <td height="25" width="200">&nbsp;</td>
        </tr>
      </table>
    </td>
    <td height="110" width="238" background="images/01.gif"><img src="images/index_pic.gif" width="238" height="110"></td>
  </tr>
  <tr> 
    <td colspan="2" height="25"><img src="images/index_top2.gif" width="778" height="25"></td>
  </tr>
</table>
<table width="778" border="0" cellspacing="0" cellpadding="0" align="center" background="images/index_lmbg.gif" height="50">
  <tr bgcolor="#c4c4c4" height="5">
    <td>&nbsp;&nbsp;
	  <div align="left"><b>
<!--Language-->
<!--Something Here-->
		</b> 
	  </div>
	</td>
  </tr>
  <tr> 
    <td valign="top"> 
      <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" height="28">
        <tr> 
		<td width="10%"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28" background="images/index_lm.gif">
              <tr> 
                <td width="100%"> 
                  <div align="center"><b><a href="#"><font color="#FFFFFF">首页</font></a></b> 
                  </div>
                </td>
              </tr>
            </table>
          </td>
<!--Button1.Content.Begin-->
          <td width="16%"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28" background="images/index_lm.gif">
              <tr> 
                <td width="100%"> 
                  <div align="center"><b>
<!--Button1.Link-->
<a href="adm_book.jsp">
<font color="#FFFFFF">
<!--Button1-->
现有图书管理
</font></a></b> 
                  </div>
                </td>
              </tr>
            </table>
          </td>
<!--Button1.Content.End-->

<!--Button2.Content.Begin-->
          <td width="14%"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28" background="images/index_lm.gif">
              <tr> 
                <td width="100%"> 
                  <div align="center"><b>
<!--Button2.Link-->
<a href="adm_addbook.jsp">
<font color="#FFFFFF">
<!--Button2-->
添加新图书
                          </font></a></b></div>
                </td>
              </tr>
            </table>
          </td>
<!--Button2.Content.End-->

<!--Button3.Content.Begin-->
          <td width="16%"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28" background="images/index_lm.gif">
              <tr> 
                <td width="100%"> 
                  <div align="center"><b>
<!--Button3.Link-->
<a href="adm_addbookclass.jsp">
<font color="#FFFFFF">
<!--Button3-->
添加图书分类 
                          </font></a></b></div>
                </td>
              </tr>
            </table>
          </td>
<!--Button3.Content.End-->

<!--Button4.Content.Begin-->
          <td width="12%"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28" background="images/index_lm.gif">
              <tr> 
                <td width="100%"> 
                  <div align="center"><b>
<!--Button4.Link-->
<a href="adm_order.jsp">
<font color="#FFFFFF">
<!--Button4-->
订单管理 
                          </font></a></b></div>
                </td>
              </tr>
            </table>
          </td>
<!--Button4.Content.End-->

<!--Button5.Content.Begin-->
          <td width="12%"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28" background="images/index_lm.gif">
              <tr> 
                <td width="100%"> 
                  <div align="center"><b>
<!--Button5.Link-->
<a href="adm_user.jsp">
<font color="#FFFFFF">
<!--Button5-->
用户管理 
                          </font></a></b></div>
                </td>
              </tr>
            </table>
          </td>
<!--Button5.Content.End-->


<!--Button5.Content.Begin-->
          <td width="10%"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28" background="images/index_lm.gif">
              <tr> 
                <td width="100%"> 
                  <div align="center"><b>
<!--Button5.Link-->
<a href="adm_login.jsp">
<font color="#FFFFFF">
<!--Button5-->
登录 
                          </font></a></b></div>
                </td>
              </tr>
            </table>
          </td>
<!--Button5.Content.End-->
<!--Button5.Content.Begin-->
          <td width="10%"> 
            <table width="100%" border="0" cellspacing="0" cellpadding="0" height="28" background="images/index_lm.gif">
              <tr> 
                <td width="100%"> 
                  <div align="center"><b>
<!--Button5.Link-->
<a href="adm_logout.jsp">
<font color="#FFFFFF">
<!--Button5-->
退出 
                          </font></a></b></div>
                </td>
              </tr>
            </table>
          </td>
<!--Button5.Content.End-->



        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="778"  cellspacing="1"  align="center" bgcolor="#E4EDFB">

          
              
             