<%@ page contentType="text/html; charset=gb2312" %>                       
 
           <tr>
            <table width="778" border="0"  cellpadding="0" align="center" bgcolor="#E4EDFB">
             <tr> 
                <td width="39.9"></td><td bgcolor="#000000" width="700.2"><img src="images/Spacer.gif" width="1" height="1"></td><td width="39.9"></td>
            </tr>
            <tr>
               <td hight="5">&nbsp;</td>
            </tr>
              
              </table>                
           
  </tr>
  
</table>
<table width="778" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td><img src="images/index_bottom.gif" width="778" height="80"></td>
  </tr>
</table>
</BODY>
</HTML>
